package com.eventledger.account.contract;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.eventledger.account.model.TransactionType;
import com.eventledger.account.repository.AccountRepository;
import com.eventledger.account.repository.TransactionRepository;
import com.eventledger.account.service.AccountService;
import com.eventledger.account.service.TransactionCommand;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.Environment;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Provider side of the contract (bonus: Pact). Replays every interaction from
 * pacts/event-gateway-account-service.json — generated by the Gateway's
 * AccountServicePactTest — against the real service booted on a random port.
 * State handlers seed H2 to match each interaction's provider state. If this
 * service changes its wire contract in a way the Gateway depends on, this
 * test goes red without needing the two-service end-to-end run.
 */
@Provider("account-service")
@PactFolder("../pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class GatewayContractVerificationTest {

    static {
        System.setProperty("pact_do_not_track", "true");
    }

    private static final TransactionCommand PACT_TRANSACTION = new TransactionCommand(
            "evt-pact-1", TransactionType.CREDIT, new BigDecimal("150.00"), "USD",
            Instant.parse("2026-05-15T14:02:11Z"));

    @Autowired
    private Environment environment;

    @Autowired
    private AccountService accountService;

    @Autowired
    private AccountRepository accountRepository;

    @Autowired
    private TransactionRepository transactionRepository;

    @BeforeEach
    void setTarget(PactVerificationContext context) {
        int port = Integer.parseInt(environment.getProperty("local.server.port"));
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifiesEveryPactInteraction(PactVerificationContext context) {
        context.verifyInteraction();
    }

    private void wipe() {
        transactionRepository.deleteAll(); // child rows first (FK to accounts)
        accountRepository.deleteAll();
    }

    @State("transaction evt-pact-1 has not been applied")
    void noTransactionApplied() {
        wipe();
    }

    @State("transaction evt-pact-1 was already applied to account acct-pact")
    void transactionAlreadyApplied() {
        wipe();
        accountService.apply("acct-pact", PACT_TRANSACTION);
    }

    @State("account acct-pact exists with balance 150.00 USD")
    void accountExists() {
        wipe();
        accountService.apply("acct-pact", PACT_TRANSACTION);
    }

    @State("account acct-missing does not exist")
    void accountMissing() {
        wipe();
    }
}
